### ISSUE TITLE
Creating a new service

### ISSUE THREAD

**Issue by dano2** [kevinblanco/drupal-ionic#1]
Thanks for creating this drupal-ionic app. I'm new to drupal and ionic. When I go to add a service, the "Server" drop down menu is empty? It's required field. I can't find any info about it. 
The form is at: admin/structure/services/add
The field description is: "Select a the server that should be used to handle requests to this endpoint."

Any suggestions?

**Comment by signalpoint** [comment]
@dano2 You need to install the REST Server module that comes with the Services module.

**Comment by dano2** [comment]
Thanks signal. That worked! If only the Service's help file would have just said that :(
I followed the rest of the instructions, but sadly when I go to create an account I get "There has been an error creating your account". The access file shows '"POST /api/v1/user/register HTTP/1.1" 404'. Everything is installed, configured and saved. Cache's cleared. 

app_config.constant('drupal_instance','http://mydomain.com/');
app_config.constant('api_endpoint','api/v1/');  //path to endpoint configured on server is api/v1/

Also, drupal saves the CORS configuration on one line. Not sure that matters. So... "api/_|_ \* \* POST|Origin,X-Requested-With,Content-Type,Accept"

Did I miss something obvious that would cause the 404?
